version: '3'

services:
  node-app:
    build: .
    container_name: node-app
    volumes:
     - .:/home/node/api
     - /home/node/api/node_modules
    entrypoint: dockerize -wait tcp://database:3306 -timeout 30s npm run start
    ports:
      - 3000:3000
    depends_on:
      - database
  
  database:
    image: mysql:5.7
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_api
  
  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    

